### ISSUE TITLE
hasImmediateDependency util should handle a yaml entry with no items

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/dart_dev#115]
Example yaml:
```yaml
name: package
version: 0.0.0
dependencies:
```

Currently the coverage task will fail on this when checking for `coverage` as an immediate dependency:

```
$ pub run dart_dev coverage
Unhandled exception:
The null object does not have a getter 'keys'.

NoSuchMethodError: method not found: 'keys'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      StandardPlatformUtil.hasImmediateDependency (package:dart_dev/src/platform_util/standard_platform_util.dart:30:56)
#3      hasImmediateDependency (package:dart_dev/src/platform_util/api.dart:25:29)
#4      CoverageCli.run.<run_async_body> (package:dart_dev/src/tasks/coverage/cli.dart:55:10)
#5      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#6      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#7      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#8      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

The `hasImmediateDependency` util should handle a yaml map with no items.

**Comment by evanweible-wf** [comment]
Duplicate of #54
