### ISSUE TITLE
CP-2121 Update copy-license task to handle non utf-8 encodable files

### ISSUE THREAD

**Issue by jayudey-wf** [Workiva/dart_dev#128]
If you run the copy-license task in a directory that has non utf-8 encodable files the following stack trace is thrown.

```
LS2-2:dart_project jayudey$ ddev copy-license
Unhandled exception:
FileSystemException: Failed to decode data using encoding 'utf-8', path = 'lib/src/.DS_Store'
#0      _File._tryDecode (dart:io/file_impl.dart:498)
#1      _File.readAsStringSync (dart:io/file_impl.dart:507)
#2      hasLicense (package:dart_dev/src/tasks/copy_license/api.dart:71:30)
#3      applyLicense (package:dart_dev/src/tasks/copy_license/api.dart:55:7)
#4      copyLicense.<anonymous closure>.<anonymous closure> (package:dart_dev/src/tasks/copy_license/api.dart:44:11)
#5      Iterable.forEach (dart:core/iterable.dart:218)
#6      copyLicense.<anonymous closure> (package:dart_dev/src/tasks/copy_license/api.dart:40:11)
#7      List.forEach (dart:core-patch/growable_array.dart:233)
#8      copyLicense (package:dart_dev/src/tasks/copy_license/api.dart:35:15)
#9      CopyLicenseCli.run.<run_async_body> (package:dart_dev/src/tasks/copy_license/cli.dart:39:9)
#10     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by maxwellpeterson-wf** [comment]
Fixed in #129
