### ISSUE TITLE
CPLAT-5205 Corner case : dart_dev will fail when pubspec has no dependencies

### ISSUE THREAD

**Issue by dustinlessard-wf** [Workiva/dart_dev#259]
```shell
wf14358:new_project dustinlessard$ pub run dart_dev docs --no-open
Unhandled exception:
NoSuchMethodError: The getter 'keys' was called on null.
Receiver: null
Tried calling: keys
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      StandardPlatformUtil.hasImmediateDependency (package:dart_dev/src/platform_util/standard_platform_util.dart:31:56)
#3      hasImmediateDependency (package:dart_dev/src/platform_util/api.dart:25:29)
#4      DocsCli.run (package:dart_dev/src/tasks/docs/cli.dart:38:10)
<asynchronous suspension>
#5      _run (package:dart_dev/src/dart_dev_cli.dart:173:29)
<asynchronous suspension>
#6      dev (package:dart_dev/src/dart_dev_cli.dart:83:9)
<asynchronous suspension>
#7      main (file:///Users/dustinlessard/Workiva/demos/new_project/tool/dev.dart:13:9)
<asynchronous suspension>
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by rmconsole2-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click a type to create one automatically: <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/259/addTicketToTitle/Task/">Task</a>, <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/259/addTicketToTitle/Bug/">Bug</a>, <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/259/addTicketToTitle/Improvement/">Improvement</a>

**Comment by evanweible-wf** [comment]
Fixed in v3.
