### ISSUE TITLE
CP-2132 ddev format stack trace isn't very helpful

### ISSUE THREAD

**Issue by markerickson-wf** [Workiva/dart_dev#87]
```
library foo;

class Foo {

    void myBadClosure() {}}

}
```

If you try to format this with dart_dev, you get a stack trace that looks like:

```
$ ddev format

::: pub run dart_style:format -l 80 -w foo/
    Formatting directory foo/:
Unhandled exception:
Uncaught Error: Could not format because the source could not be parsed:
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

but dartfmt gives a much more helpful stack like:

```
$ dartfmt -w foo/
Formatting directory foo/:
Could not format because the source could not be parsed:

line 7, column 1 of foo/foo.dart: Expected a method, getter, setter or operator declaration
}
^
line 7, column 1 of foo/foo.dart: Unexpected token '}'
}
^
```

**Comment by maxwellpeterson-wf** [comment]
This appears to be due to an older version of `dart_style` being used in the package that you were using `dart_dev` for.
